### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by jkock** [finanalyst/grav-plugin-sequential-form#1]
Hey,

Your plugin is exactly what I was looking for.
I've tried implementing your example, but unfortunately the form does not continue to the 'Terms' page. If I turn around the order in routes, the form does not process to the 'video' page, but does display the `Terms`  page correctly

Also, hitting a button with "sequence_reset" throws an error 

`"Call to a member function getData() on boolean"`

on line 68

`$sequence = $sumForm->getData()->toArray()['_sequence'];`

**Comment by finanalyst** [comment]
@jkock 
I tried to reply to your issue.
There was a major error in processing the processes from the initial form.
I have resolved the bugs identified.
The plugin now works with the example in the README. (I set up a clean Grav with minimal plugins and this plugin, and used the example for the test. It works as designed.)
Please let me know if works for you.

**Comment by jkock** [comment]
The form now continues! Thanks for the fix.
Clicking the reset sequence button however had an error with an undefined variable $url. Please see this pull request to fix it: https://github.com/finanalyst/grav-plugin-sequential-form/pull/2
